### PR TITLE
Fixed classic theme

### PR DESCRIPTION
**Pull request by thokis**
This commit modified the classic theme to match the provided screenshot.

Before the changes:

image

After the changes:

image

### CODE REVIEW

**Comment by teamcons** [comment]
Hello

Wow, a commit ! Didnt know people actually used this.
I will check this when im home - But before i try first :

Classic theme as it is since this morning supposedly works taking into account the dock following this merged Pull Request from yesterday: https://github.com/elementary/dock/pull/328
Before then, i couldnt style it like the latter, because before this merge the dock window and background were fused.

Current one works as the latter screenshot for me.
Could you confirm you made this from the "Post-merge" Dock code ?

In all case i will check your branch

**Comment by teamcons** [comment]
Nope, i get this, with your changes

Bildschirmfoto von 2024-12-10 19 02 01

**Comment by thokis** [comment]
Hmm, really weird to be honest. I even installed elementary OS 8 new on a machine and can only get the right look with my changes.

EDIT:
How can i confirm which version of the dock i am running? There are no new packages available via `apt update` or in the AppCenter.

EDIT2:
[Kooha-2024-12-10-21-06-35.webm](https://github.com/user-attachments/assets/f1b14c8e-2b47-46a4-acaf-15f007701684)

**Comment by teamcons** [comment]
> Hmm, really weird to be honest. I even installed elementary OS 8 new on a machine and can only get the right look with my changes.
> 
> EDIT: How can i confirm which version of the dock i am running? There are no new packages available via `apt update` or in the AppCenter.
> 
> EDIT2: [Kooha-2024-12-10-21-06-35.webm](https://github.com/user-attachments/assets/f1b14c8e-2b47-46a4-acaf-15f007701684)

I believe you ! :) No need to show a video
Yes, i think the difference is because i am running the next dock update. Which i built from source - I often do that for testing
I believe it is "8.0.2" ? It isn't available yet.

i wanted to advertise the classic theme once it lands, because it needed some changes that will land in said update.
So you were caught up in the middle, before dock release - I did not expect someone would try before it arrives. It should arrive in the next days
My apologies for the annoyance.

We could add in the README a link to your fix, and explain the current one is for next dock update?
Moving forward i will be a bit more careful with commits

**Comment by thokis** [comment]
No need to apologize ^^
Seems fine for me to mention it in the README. Maybe you could specify that a specific branch or tag could be used with my commit or something like this. I just think it is a little bit confusing for a normal user why the theme does not look like the screenshots ^^

**Comment by thokis** [comment]
Will close this MR, because the README mentions the problem this MR solves ^^

**Comment by teamcons** [comment]
As you wish ! Ive linked to your PR so people can do your adjustement, up until the dock update

Ive done some refinement to the Classic theme - that gradient was way too strong
So if you want you can update yours (and change for the current dock version)

i am not sure when the dock update lands. Can you click on the icons above the bar, or is it buggy ?

**Pull request closed without merging**
